language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install --quiet -g "gulpjs/gulp-cli#4.0" karma bower
- npm install
- bower install
script: gulp build
deploy:
  provider: s3
  access_key_id: AKIAJJAIUMS4RHS55K4A
  secret_access_key:
    secure: fWAjggYp53F3msVzTIy1kGUmxBSQKCyhV2azny7+WwA1mlngUoNsZyIXksPOVa4m1rx/wkWcXvxzz/IO/EPHlc8cP4I0Fthvm/vowXT6UaF00GyFC2xhuIFK7VDeZXIW0z1RjdG/ncqLO3JfS7+fWG1n82Is7BJXd+9MYDBtNF0+IY1tTMf3hMKnxgOAkGTgOEJq2ZmJq6z2DMAQS/OSyJ3KjUXBC9W0adfqcmcGDJxYm/Vw97GL/hqCe8zUuxGhhm7ZEnCirNBeLw2kbV5UD8SOXzohp1cWvdTMCtnJSOxRPqYTyX4mjLWynw4wDsPaXVhUbP737fz/kWQEZtmGZznnt8B6gyjdTtSLXQinaPF+XQgzGKEC1ivKZEkH0m92TdaLSjw0Yyujh5If1LH70JWUbJRCPxWWXQw+xR4vs2sYRMz8mdfCmsIeIyo1lNbHYcBFkmgWTTwBXp3hyw5pH9pbUaMJO/N0ldb4E8D6CntOw9C6zzs4zKrlTpD3T0AAmITLyRa1R8FgATnijrzWFU82ddW1hv7bapT6UyRpHjYj7DSVPvCP4KN0DcddMcnJwsy+f8lbbizN2oCQb8hDZgHAt4R4q9Esr8P2w9Nr4PiSyfi/IikJd5wzRkqR1zIPdVG++jmP3aqRamoNUmJ5qIgtNsLpfDOcN2PwPlmdPpQ=
  bucket: 451ordercloudtest
  region: us-west-2
  skip_cleanup: true
  endpoint: s3-website-us-west-2.amazonaws.com
  local-dir: build
